export const Colors = {
  light: {
    background: '#ffffff',
    backgroundSecondary: '#f0f0f0',
    text: '#000000',
    placeholder: '#a0a0a0',
    button: '#6200ee',
    buttonText: '#ffffff',
    itemBackground: '#ffffff',
    completedText: '#a0a0a0',
    headerBackground: '#ffffff',
    border: '#e0e0e0',
    inputBackground: '#ffffff',
  },
  dark: {
    background: '#121212',
    backgroundSecondary: '#1e1e1e',
    text: '#ffffff',
    placeholder: '#808080',
    button: '#bb86fc',
    buttonText: '#000000',
    itemBackground: '#1e1e1e',
    completedText: '#808080',
    headerBackground: '#1e1e1e',
    border: '#333333',
    inputBackground: '#1e1e1e',
  },
};